---
galaxy_info:
  author: Roderik van der Veer
  description: Ansible profile role for developers
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - norton.superlumic-computername
  - norton.superlumic-cli
  - norton.superlumic-homebrew
  - norton.superlumic-mysql
  - norton.superlumic-php
  - norton.superlumic-sublimetext
  - norton.superlumic-skylab
  - norton.superlumic-node
  - norton.superlumic-vim
  - profile-all
